package com.eddies.app.data.repo

import android.content.Context
import com.eddies.app.data.db.dao.AssetDao
import com.eddies.app.data.db.entity.AssetEntity
import com.eddies.app.data.prefs.SettingsDataStore
import com.eddies.app.data.price.AggregatorSource
import com.eddies.app.domain.Asset
import com.eddies.app.domain.AssetClass
import com.eddies.app.data.db.entity.AssetSourceRefEntity
import com.eddies.app.data.stocks.TradegateSource
import com.eddies.app.domain.AssetIds
import com.eddies.app.domain.Isin
import com.eddies.app.domain.PriceSourceId
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import javax.inject.Inject
import javax.inject.Singleton

@Serializable
private data class SeedEntry(
    val id: String,
    val name: String,
    val symbol: String,
    val rank: Int? = null,
    val icon: String? = null,
)

/**
 * Assets the app knows about, seeded offline and extended online.
 *
 * The seed ships in the APK (assets/asset_seed.json, generated by
 * scripts/refresh-icons.sh) so the very first search is instant and, more to the
 * point, reaches no network. Typing a coin name is a disclosure of what someone
 * is about to buy; that should not leave the phone by default.
 */
@Singleton
class AssetRepository @Inject constructor(
    @ApplicationContext private val context: Context,
    private val assetDao: AssetDao,
    private val settings: SettingsDataStore,
    private val aggregator: AggregatorSource,
    private val yahoo: com.eddies.app.data.stocks.YahooApi,
    private val tradegate: com.eddies.app.data.stocks.TradegateSource,
    private val sourceRefDao: com.eddies.app.data.db.dao.AssetSourceRefDao,
    private val json: Json,
) {

    /** Loads the bundled seed once per seed version. Cheap to call on every launch. */
    suspend fun ensureSeeded() = withContext(Dispatchers.IO) {
        val current = settings.current()
        if (current.seedVersion >= SEED_VERSION && assetDao.count() > 0) return@withContext

        val raw = runCatching {
            context.assets.open(SEED_FILE).bufferedReader().use { it.readText() }
        }.getOrNull() ?: return@withContext

        val entries = runCatching { json.decodeFromString<List<SeedEntry>>(raw) }.getOrNull().orEmpty()
        if (entries.isEmpty()) return@withContext

        assetDao.upsert(
            entries.map { e ->
                AssetEntity(
                    id = AssetIds.crypto(e.id),
                    assetClass = AssetClass.CRYPTO,
                    symbol = e.symbol.uppercase(),
                    name = e.name,
                    decimals = decimalsFor(e.symbol),
                    iconSlug = e.icon,
                    rank = e.rank,
                )
            },
        )
        settings.setSeedVersion(SEED_VERSION)
    }

    suspend fun byId(assetId: String): Asset? = assetDao.byId(assetId)?.toDomain()

    suspend fun byIds(assetIds: Collection<String>): Map<String, Asset> =
        assetDao.byIds(assetIds.toList()).associate { it.id to it.toDomain() }

    suspend fun topByRank(limit: Int = 100): List<Asset> = assetDao.topByRank(limit).map { it.toDomain() }

    /**
     * Offline search first. The online lookup only runs when the local set has
     * nothing and the user has opted into remote calls, so the default path
     * discloses nothing about what they are looking for.
     */
    suspend fun search(term: String, allowRemote: Boolean = false): List<Asset> {
        val trimmed = term.trim()
        if (trimmed.isEmpty()) return topByRank(50)

        val local = assetDao.search(trimmed).map { it.toDomain() }
        if (local.isNotEmpty() || !allowRemote) return local

        val remote = aggregator.searchCoins(trimmed)
        if (remote.isNotEmpty()) {
            assetDao.upsert(remote.map { it.toEntity() })
        }
        return remote
    }

    /**
     * Shares, which are always looked up online.
     *
     * No offline seed for these: there are tens of thousands of listings across
     * dozens of exchanges, and bundling a useful subset is not possible the way
     * it is for the few hundred coins that matter. Kept as a separate call so
     * the coin search stays offline and private by default, and a stock lookup
     * is an explicit act.
     */
    suspend fun searchStocks(term: String): List<Asset> {
        val trimmed = term.trim()
        if (trimmed.length < 2) return emptyList()
        val results = yahoo.search(trimmed)
        if (results.isNotEmpty()) assetDao.upsert(results.map { it.toEntity() })
        return results
    }

    /**
     * Confirms Tradegate lists the ISIN, names it via Yahoo, and records both
     * source refs so live prices and history can come from different places.
     */
    suspend fun resolveTradegate(isin: String): TradegateLookup {
        val quote = tradegate.quote(isin) ?: return TradegateLookup.NotListed

        val id = AssetIds.stock(TradegateSource.EXCHANGE, isin)
        // Yahoo search accepts an ISIN and answers with the listing, which is
        // where the human-readable name comes from. If it is down we still have
        // a tradeable instrument and a price, so the ISIN stands in as the name.
        val match = runCatching { yahoo.search(isin, limit = 1) }.getOrNull()?.firstOrNull()

        val asset = Asset(
            id = id,
            assetClass = AssetClass.STOCK,
            symbol = match?.symbol ?: isin,
            name = match?.name ?: isin,
            decimals = 4,
        )
        assetDao.upsert(asset.toEntity(tracked = true))

        val refs = mutableListOf(
            AssetSourceRefEntity(id, PriceSourceId.TRADEGATE, isin, TradegateSource.CURRENCY),
        )
        // The Yahoo symbol is what the charts and the split history hang off.
        match?.symbol?.let { refs += AssetSourceRefEntity(id, PriceSourceId.YAHOO, it, null) }
        runCatching { sourceRefDao.upsert(refs) }

        return TradegateLookup.Found(asset, quote.last)
    }

    suspend fun setTracked(assetId: String, tracked: Boolean) = assetDao.setTracked(assetId, tracked)

    /**
     * Display precision. Not the chain's real decimal count, which is 18 for most
     * tokens and unreadable: this is how many places a balance is shown to.
     */
    private fun decimalsFor(symbol: String): Int = when (symbol.uppercase()) {
        "BTC", "WBTC", "XMR" -> 8
        "ETH", "WETH", "BNB", "SOL" -> 6
        "USDT", "USDC", "DAI", "BUSD" -> 2
        else -> 6
    }

    private companion object {
        const val SEED_FILE = "asset_seed.json"

        /** Bump when the seed file changes so existing installs re-import it. */
        const val SEED_VERSION = 1
    }
}

internal fun AssetEntity.toDomain() = Asset(
    id = id,
    assetClass = assetClass,
    symbol = symbol,
    name = name,
    decimals = decimals,
    iconSlug = iconSlug,
    rank = rank,
)

internal fun Asset.toEntity(tracked: Boolean = false) = AssetEntity(
    id = id,
    assetClass = assetClass,
    symbol = symbol,
    name = name,
    decimals = decimals,
    iconSlug = iconSlug,
    rank = rank,
    tracked = tracked,
)

/**
 * Looks up an instrument on Tradegate by ISIN.
 *
 * Kept separate from the ticker search because Tradegate has no search endpoint
 * and no ticker: it is keyed by ISIN only. That matches how a European broker
 * statement reads anyway, so pasting the ISIN is the natural act rather than a
 * workaround.
 *
 * Two calls, both of which have to work for the result to be useful: Tradegate
 * confirms it actually lists the instrument and gives a live price, and Yahoo
 * resolves the ISIN to a name and a symbol. That symbol is stored as a source
 * ref so charts and splits can come from Yahoo, since Tradegate serves a
 * snapshot and no history at all.
 */
suspend fun AssetRepository.lookupTradegate(rawIsin: String): TradegateLookup {
    val isin = Isin.normalise(rawIsin)
    if (!Isin.looksLikeIsin(isin)) return TradegateLookup.Invalid("That is not an ISIN. They look like NL0010273215.")
    if (!Isin.isValid(isin)) return TradegateLookup.Invalid("That ISIN's check digit is wrong. Check for a typo.")
    return resolveTradegate(isin)
}

sealed interface TradegateLookup {
    data class Found(val asset: Asset, val price: java.math.BigDecimal) : TradegateLookup
    data class Invalid(val reason: String) : TradegateLookup
    data object NotListed : TradegateLookup
    data object Unreachable : TradegateLookup
}
