package com.eddies.app.data.repo

import android.content.Context
import com.eddies.app.data.db.dao.AssetDao
import com.eddies.app.data.db.entity.AssetEntity
import com.eddies.app.data.prefs.SettingsDataStore
import com.eddies.app.data.price.AggregatorSource
import com.eddies.app.domain.Asset
import com.eddies.app.domain.AssetClass
import com.eddies.app.domain.AssetIds
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import javax.inject.Inject
import javax.inject.Singleton

@Serializable
private data class SeedEntry(
    val id: String,
    val name: String,
    val symbol: String,
    val rank: Int? = null,
    val icon: String? = null,
)

/**
 * Assets the app knows about, seeded offline and extended online.
 *
 * The seed ships in the APK (assets/asset_seed.json, generated by
 * scripts/refresh-icons.sh) so the very first search is instant and, more to the
 * point, reaches no network. Typing a coin name is a disclosure of what someone
 * is about to buy; that should not leave the phone by default.
 */
@Singleton
class AssetRepository @Inject constructor(
    @ApplicationContext private val context: Context,
    private val assetDao: AssetDao,
    private val settings: SettingsDataStore,
    private val aggregator: AggregatorSource,
    private val json: Json,
) {

    /** Loads the bundled seed once per seed version. Cheap to call on every launch. */
    suspend fun ensureSeeded() = withContext(Dispatchers.IO) {
        val current = settings.current()
        if (current.seedVersion >= SEED_VERSION && assetDao.count() > 0) return@withContext

        val raw = runCatching {
            context.assets.open(SEED_FILE).bufferedReader().use { it.readText() }
        }.getOrNull() ?: return@withContext

        val entries = runCatching { json.decodeFromString<List<SeedEntry>>(raw) }.getOrNull().orEmpty()
        if (entries.isEmpty()) return@withContext

        assetDao.upsert(
            entries.map { e ->
                AssetEntity(
                    id = AssetIds.crypto(e.id),
                    assetClass = AssetClass.CRYPTO,
                    symbol = e.symbol.uppercase(),
                    name = e.name,
                    decimals = decimalsFor(e.symbol),
                    iconSlug = e.icon,
                    rank = e.rank,
                )
            },
        )
        settings.setSeedVersion(SEED_VERSION)
    }

    suspend fun byId(assetId: String): Asset? = assetDao.byId(assetId)?.toDomain()

    suspend fun byIds(assetIds: Collection<String>): Map<String, Asset> =
        assetDao.byIds(assetIds.toList()).associate { it.id to it.toDomain() }

    suspend fun topByRank(limit: Int = 100): List<Asset> = assetDao.topByRank(limit).map { it.toDomain() }

    /**
     * Offline search first. The online lookup only runs when the local set has
     * nothing and the user has opted into remote calls, so the default path
     * discloses nothing about what they are looking for.
     */
    suspend fun search(term: String, allowRemote: Boolean = false): List<Asset> {
        val trimmed = term.trim()
        if (trimmed.isEmpty()) return topByRank(50)

        val local = assetDao.search(trimmed).map { it.toDomain() }
        if (local.isNotEmpty() || !allowRemote) return local

        val remote = aggregator.searchCoins(trimmed)
        if (remote.isNotEmpty()) {
            assetDao.upsert(remote.map { it.toEntity() })
        }
        return remote
    }

    suspend fun setTracked(assetId: String, tracked: Boolean) = assetDao.setTracked(assetId, tracked)

    /**
     * Display precision. Not the chain's real decimal count, which is 18 for most
     * tokens and unreadable: this is how many places a balance is shown to.
     */
    private fun decimalsFor(symbol: String): Int = when (symbol.uppercase()) {
        "BTC", "WBTC", "XMR" -> 8
        "ETH", "WETH", "BNB", "SOL" -> 6
        "USDT", "USDC", "DAI", "BUSD" -> 2
        else -> 6
    }

    private companion object {
        const val SEED_FILE = "asset_seed.json"

        /** Bump when the seed file changes so existing installs re-import it. */
        const val SEED_VERSION = 1
    }
}

internal fun AssetEntity.toDomain() = Asset(
    id = id,
    assetClass = assetClass,
    symbol = symbol,
    name = name,
    decimals = decimals,
    iconSlug = iconSlug,
    rank = rank,
)

internal fun Asset.toEntity(tracked: Boolean = false) = AssetEntity(
    id = id,
    assetClass = assetClass,
    symbol = symbol,
    name = name,
    decimals = decimals,
    iconSlug = iconSlug,
    rank = rank,
    tracked = tracked,
)
